help:
	@echo "Para compilar: > make tp3 "
	@echo "Para ejecutar: > make run "
	@echo "Para ejecutar con valgrind: > make valrun"


tp3: main.cpp\
             Vertex.cpp Vertex.h\
             List.h Node.h\
             Cell.cpp Cell.h\
             Mountain.cpp Mountain.h\
             Lake.cpp Lake.h\
             Cliff.cpp Cliff.h\
             Volcano.cpp Volcano.h\
             Road.cpp Road.h\
             TheVoid.cpp TheVoid.h\
             Object.h Object.cpp\
             Being.h Being.cpp\
             Human.h Human.cpp\
             Bullet.h Bullet.cpp\
             Cross.cpp Cross.h\
             Element.h\
             HolyWater.h HolyWater.cpp\
             Monster.h\
             Nosferatu.h Nosferatu.cpp\
             Vampire.h Vampire.cpp\
             Shotgun.h Shotgun.cpp\
             Stake.h Stake.cpp\
             Hunter.h Hunter.cpp\
             Vampirella.h Vampirella.cpp\
             Vanesa.h Vanesa.cpp\
             Zombie.h Zombie.cpp\
             Floyd.cpp Floyd.h\
             Battle.cpp Battle.h\
             Map.h Matrix.h\
             estado.txt tablero.txt\
             BoardFile.cpp BoardFile.h\
             ObjectFile.cpp ObjectFile.h\
             FileManager.cpp FileManager.h\
             SaveGameFile.cpp SaveGameFile.h\
             ObjectIncludes.h constantsNames.h\
             ObjectCreator.cpp ObjectCreator.h\
             Map.cpp\
             colors.h\
             Gotoxy.h MapCreator.cpp MapCreator.h
	g++ -o tp3 main.cpp\
                            Vertice.cpp Vertice.h\
                            Lista.h Nodo.h\
                            Cell.cpp Cell.h\
                            Mountain.cpp Mountain.h\
                            Lake.cpp Lake.h\
                            Cliff.cpp Cliff.h\
                            Volcano.cpp Volcano.h\
                            Road.cpp Road.h\
                            TheVoid.cpp TheVoid.h\
                            Object.h Object.cpp\
                            Being.h Being.cpp\
                            Human.h Human.cpp\
                            Bullet.h Bullet.cpp\
                            Cross.cpp Cross.h\
                            Element.h\
                            HolyWater.h HolyWater.cpp\
                            Monster.h\
                            Nosferatu.h Nosferatu.cpp\
                            Vampire.h Vampire.cpp\
                            Shotgun.h Shotgun.cpp\
                            Stake.h Stake.cpp\
                            Hunter.h Hunter.cpp\
                            Vampirella.h Vampirella.cpp\
                            Vanesa.h Vanesa.cpp\
                            Zombie.h Zombie.cpp\
                            Floyd2.cpp Floyd2.h\
                            Battle.cpp Battle.h\
                            Map.h Matrix.h\
                            BoardFile.cpp BoardFile.h\
                            ObjectFile.cpp ObjectFile.h\
                            FileManager.cpp FileManager.h\
                            SaveGameFile.cpp SaveGameFile.h\
                            ObjectIncludes.h constansNames.h\
                            ObjectCreator.cpp ObjectCreator.h\
                            Map.cpp\
                            colors.h\
                            Gotoxy.h MapCreator.cpp MapCreator.h

run:
	./tp3

valrun:
	valgrind ./tp3